hwstl: main.cc cube.h cylinder.h 
		g++ main.cc cube.h cylinder.h -o hwstl

main.o: main.cc cube.h cylinder.h
		g++ -c main.cc

#circle.o: circle.cc circle.hh
#		g++ -c circle.cc

clean: 
		rm *.o hwstl
